# Generated by Django 6.0.4 on 2026-04-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0002_systemstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HackathonState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_started', models.BooleanField(default=False)),
                ('is_finished', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Hackathon State',
            },
        ),
        migrations.DeleteModel(
            name='SystemState',
        ),
        migrations.RemoveField(
            model_name='teamprogress',
            name='total_points',
        ),
        migrations.AddField(
            model_name='teamprogress',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teamprogress',
            name='current_code',
            field=models.TextField(default='# Write Python code here\n# Use print() for output\n'),
        ),
        migrations.AlterField(
            model_name='teamprogress',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
