# Generated by Django 6.0.4 on 2026-05-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0005_problem_difficulty_problem_function_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprogress',
            name='starter_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
