# Generated by Django 6.0.4 on 2026-05-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0006_teamprogress_starter_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamprogress',
            name='starter_code',
        ),
        migrations.AddField(
            model_name='problem',
            name='starter_code',
            field=models.TextField(blank=True, default=''),
        ),
    ]
