# Generated by Django 6.0.4 on 2026-05-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0009_bonusquestion_bonussubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_variable',
            field=models.CharField(default='n', help_text="Variable name injected into student code e.g. 'n', 'data', 'nums'", max_length=100),
        ),
    ]
