# Generated by Django 5.2.4 on 2026-05-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0011_hackathonstate_is_paused_hackathonstate_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusquestion',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bonusquestion',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
