# Generated by Django 5.2.4 on 2026-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0013_hackathonstate_hints_enabled_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonstate',
            name='ai_model',
            field=models.CharField(choices=[('gemini-2.5-flash-preview-05-20', 'Gemini 2.5 Flash Preview'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro Preview'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro')], default='gemini-2.0-flash', help_text='Gemini model used for AI hints — change takes effect immediately', max_length=100),
        ),
    ]
