# Generated by Django 6.0.5 on 2026-05-28 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0022_alter_bonusquestion_id_alter_bonussubmission_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonusquestion',
            options={'ordering': ['order'], 'verbose_name': 'Bonus Question', 'verbose_name_plural': 'Bonus Questions'},
        ),
        migrations.AlterUniqueTogether(
            name='bonussubmission',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bonusquestion',
            name='appear_after_minutes',
        ),
        migrations.RemoveField(
            model_name='bonusquestion',
            name='auto_start_triggered',
        ),
        migrations.RemoveField(
            model_name='bonusquestion',
            name='max_points',
        ),
        migrations.RemoveField(
            model_name='bonusquestion',
            name='max_winners',
        ),
        migrations.RemoveField(
            model_name='bonusquestion',
            name='points_step',
        ),
        migrations.AddField(
            model_name='bonusquestion',
            name='order',
            field=models.IntegerField(default=1, help_text='Question order (1, 2, 3)'),
        ),
        migrations.AddField(
            model_name='hackathonstate',
            name='bonus_first_finisher',
            field=models.ForeignKey(blank=True, help_text='First team to solve all bonus questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_first_finish', to=settings.AUTH_USER_MODEL),
        ),
    ]
