# Generated by Django 6.0.5 on 2026-05-28 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0023_alter_bonusquestion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonstate',
            name='duration_minutes',
            field=models.IntegerField(default=120, help_text='Duration of the hackathon in minutes'),
        ),
        migrations.AlterUniqueTogether(
            name='bonussubmission',
            unique_together={('team', 'bonus')},
        ),
    ]
