# Generated by Django 6.0.4 on 2026-04-25 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False, verbose_name='Hackathon Started')),
            ],
            options={
                'verbose_name': 'Global Hackathon Control',
                'verbose_name_plural': 'Global Hackathon Control',
            },
        ),
    ]
