# Generated by Django 6.0.4 on 2026-04-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0003_hackathonstate_delete_systemstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonstate',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='When the hackathon officially starts', null=True),
        ),
    ]
