# Generated by Django 6.0.4 on 2026-05-09 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0008_problem_examples'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Bonus Round', max_length=200)),
                ('description', models.TextField()),
                ('starter_code', models.TextField()),
                ('expected_output', models.CharField(max_length=500)),
                ('input_type_hint', models.CharField(blank=True, default='', max_length=200)),
                ('max_points', models.IntegerField(default=200)),
                ('points_step', models.IntegerField(default=15)),
                ('max_winners', models.IntegerField(default=4)),
                ('duration_minutes', models.IntegerField(default=7)),
                ('appear_after_minutes', models.IntegerField(choices=[(60, 'After 1 hour'), (90, 'After 1.5 hours'), (120, 'After 2 hours')], default=120)),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Bonus Question',
                'verbose_name_plural': 'Bonus Question',
            },
        ),
        migrations.CreateModel(
            name='BonusSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_input', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('points_awarded', models.IntegerField(default=0)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platform_app.bonusquestion')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'bonus')},
            },
        ),
    ]
