# Generated by Django 5.2.4 on 2026-05-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0019_alter_bonusquestion_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonusquestion',
            name='auto_start_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bonusquestion',
            name='appear_after_minutes',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='bonusquestion',
            name='duration_minutes',
            field=models.IntegerField(default=2),
        ),
    ]
