# Generated by Django 6.0.5 on 2026-06-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0025_teamprogress_hint_text_alter_hackathonstate_ai_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprogress',
            name='tab_switches',
            field=models.IntegerField(default=0),
        ),
    ]
