# Generated by Django 6.0.4 on 2026-05-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0004_hackathonstate_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AddField(
            model_name='problem',
            name='function_name',
            field=models.CharField(default='solution', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='points',
            field=models.IntegerField(default=100),
        ),
    ]
