# Generated by Django 6.0.4 on 2026-05-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0007_remove_teamprogress_starter_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='examples',
            field=models.TextField(blank=True, default=''),
        ),
    ]
