# Generated by Django 5.2.4 on 2026-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0015_alter_hackathonstate_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonstate',
            name='ai_model',
            field=models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant'), ('llama3-70b-8192', 'Llama 3 70B'), ('llama3-8b-8192', 'Llama 3 8B'), ('gemma2-9b-it', 'Gemma 2 9B'), ('mixtral-8x7b-32768', 'Mixtral 8x7B')], default='llama-3.3-70b-versatile', help_text='Groq model used for AI hints — change takes effect immediately', max_length=100),
        ),
    ]
