# Generated by Django 5.2.4 on 2026-05-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0016_alter_hackathonstate_ai_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonstate',
            name='ai_model',
            field=models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile'), ('openai/gpt-oss-120b', 'GPT OSS 120B'), ('groq/compound', 'Groq Compound')], default='llama-3.3-70b-versatile', help_text='Groq model used for AI hints — change takes effect immediately', max_length=100),
        ),
    ]
