# Generated by Django 6.0.5 on 2026-06-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_app', '0024_hackathonstate_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamprogress',
            name='hint_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='hackathonstate',
            name='ai_model',
            field=models.CharField(choices=[('llama-3.3-70b-versatile', 'Llama 3.3 70B Versatile'), ('openai/gpt-oss-120b', 'GPT OSS 120B'), ('groq/compound', 'Groq Compound'), ('ollama/llama3', 'Ollama - Llama 3'), ('ollama/mistral', 'Ollama - Mistral'), ('openai/gpt-4o', 'OpenAI - GPT-4o')], default='llama-3.3-70b-versatile', help_text='Groq model used for AI hints — change takes effect immediately', max_length=100),
        ),
    ]
